### ISSUE TITLE
Extension seem to be broken

### ISSUE THREAD

**Issue by r-menezes** [Manueloccorso/NotionMathEditor_BrowserExtension#9]
This is an amazing tool !
I feel that I came late to the party, but for me this would be very helpful. Unfortunately, I couldn't get the extension to work on Chrome/Chromium, probably because some API changes.

Is a fix possible / expected ?

**Comment by Manueloccorso** [comment]
Hi, I'm sorry for the very late reply. At the moment I'm not working on this project anymore, I'm sorry!

**Comment by r-menezes** [comment]
No problem!
Thank you again for making this and making the code available here :)
